### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by jeanffc** [marcosvgs/my_admin#16]
Follow the error

macOS Sierra 10.12.1
rails 4.2.6
ruby 2.2.3p173

$ rails g my_admin:install
/Applications/MAMP/htdocs/my_admin/config/application.rb:10:in `<module:MyAdmin>': superclass mismatch for class Application (TypeError)
	from /Applications/MAMP/htdocs/my_admin/config/application.rb:9:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application.rb:82:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application.rb:82:in `preload'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application.rb:143:in `serve'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

**Comment by jeanffc** [comment]
I found the error

I could not use the project name 'my_admin'

So I switched to another name and solved the problem
